### ISSUE TITLE
Changelog?!

### ISSUE THREAD

**Issue by Apollon77** [intellinote/sql-client#3]
Hey,

is there a changelog somewhere for your library?

I have a project with sql-client 0.7 and wonder what changed to latest version 1.2.0 - especially breaking changes ...
Or do I need to go through all commits? :(

Thank your for some informations

**Comment by Apollon77** [comment]
I checked all commits and beside fixes and build stuff I found:
- Transaction support added in 1.1.0
- Pool stuff: you can encapsulate the `borrow` and `return` sequence with a single call, `execute` in 1.1.0 (but not a required change)
- 1.2.0 changed some testing stuff

is that correct?!

**Comment by rodw** [comment]
Hi @Apollon77 - we have not been maintaining a change log but we will going forward.

I think your summary is correct:

- Version 1.1.0 added support for transactions and a convenience `execute` method to avoid the borrow/return logic.

- The changes in Version 1.2.0 were to ensure the sql-client works properly with the latest long-term-support release of Node.js.  sql-client is now compatible with node 0.10.x, 0.12.x, 4.x and 6.x. 
  - The only end-client visible change is upgrades to some of the _optional_ third-party dependencies - https://github.com/intellinote/sql-client/commit/ca33ae7509ffc055c184e3120543f7d062ec0345
  - As you note, we had to make minor changes to some of the test code to allow the unit test suite to work with the latest version of Mocha, but that code is not even distributed with the published sql-client npm module.

As far as I know we have not introduced breaking changes in any release.

We incremented the version number in 1.1.0 so that clients that depend on the new methods can more easily reference that version.  

We incremented the version number in 1.2.0 to call attention to the new versions of the _optional_ third-party dependencies, but there were no changes to the public-facing API.

You make a good point about the change log. We'll follow that practice going forward.
